# -*- coding: utf-8 -*-
"""Amit-lectures session 11 revision

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U24YwR-UnsE9JpUj3Y7tU1XEtMlMQVn9
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

df=pd.read_csv('Mall_Customers.csv')
df
X=df.iloc[:,3:].values

df

X

wcss=[]
for i in range(1,11):
  Kmeans=KMeans(n_clusters= i, init ="k-means++",random_state=42)
  Kmeans.fit(X)
  wcss.append(Kmeans.inertia_)




plt.plot(range(1,11),wcss)
plt.title("The Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("wcss")
plt.show()

kmeans=KMeans(n_clusters=5,init="k-means++",random_state=42)
kmeans.fit(X)
y_kmeans=kmeans.predict(X)

plt.scatter(X[y_kmeans==0,0],X[y_kmeans==0,1],s=100,c='red',label="Cluster 1")
plt.scatter(X[y_kmeans==1,0],X[y_kmeans==1,1],s=100,c='green',label="Cluster 2")
plt.scatter(X[y_kmeans==2,0],X[y_kmeans==2,1],s=100,c='blue',label="Cluster 3")
plt.scatter(X[y_kmeans==3,0],X[y_kmeans==3,1],s=100,c='cyan',label="Cluster 4")
plt.scatter(X[y_kmeans==4,0],X[y_kmeans==4,1],s=100,c='magenta',label="Cluster 5")
plt.scatter(kmeans.cluster_centers_[:,1],kmeans.cluster_centers_[:,0],s=300,c="yellow",label="Centers")
plt.title("Centers of Clusters")

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from scipy.cluster.hierarchy import linkage,dendrogram
from sklearn.cluster import AgglomerativeClustering
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import metrics

df=load_iris()
data=df.data
data
#linkmethod=linkage(data,method="complete")
avg_comp=AgglomerativeClustering(n_clusters=3,linkage="complete")
avg_comp.fit(data)
#plt.figure(figsize=(100,40))
#dendrogram(linkmethod)
#plt.show()
plt.figure(figsize=(10,5))
plt.scatter(data[:,0],data[:,1],s=100,c=avg_comp.labels_)
plt.show()



























