# -*- coding: utf-8 -*-
"""Spam Filter using Naive Bayes Nick Stugard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vGKa8RrS3NI29XdsleGHPlnQ7zBE-Nu7
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score

df=pd.read_csv('spam.csv')
df

df.describe()

df.info()

df.shape

df.isnull().sum()

df.value_counts()

df.columns

df.values

df['Category'].unique()

df=df.replace({'ham':0,'spam':1})
df

y=df['Category']
x=df['Message']

y

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2)

cv=CountVectorizer()
x_train_count=cv.fit_transform(x_train.values)

model=MultinomialNB()
model.fit(x_train_count,y_train)

#'come to the party tonight'     ham
#'reward money click'     spam
email=['reward money click']
email_count=cv.transform(email)

if(model.predict(email_count)==0):
  print('ham')
else:
  print('spam')